"""api_specs and surface_endpoints

Revision ID: 1be05aad205b
Revises: ffdd5b9970bc
Create Date: 2026-09-18 07:26:18.305110
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1be05aad205b"
down_revision: str | None = "ffdd5b9970bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_specs",
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("openapi_version", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("api_version", sa.String(length=64), nullable=True),
        sa.Column("raw_document", sa.Text(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_id"),
    )
    op.create_table(
        "surface_endpoints",
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("api_spec_id", sa.UUID(), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=2048), nullable=False),
        sa.Column("operation_id", sa.String(length=300), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("request_body_content_types", sa.JSON(), nullable=False),
        sa.Column("security_schemes", sa.JSON(), nullable=False),
        sa.Column("requires_auth", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "source", sa.Enum("OPENAPI", "DECLARED", name="surface_source_enum"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["api_spec_id"], ["api_specs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "target_id", "method", "path", name="uq_surface_endpoint_target_method_path"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("surface_endpoints")
    op.drop_table("api_specs")
    # ### end Alembic commands ###
    # See the equivalent note in 5e19add79ace: op.drop_table leaves the ENUM
    # type Postgres created for this column behind.
    sa.Enum(name="surface_source_enum").drop(op.get_bind(), checkfirst=True)
