"""code scope and appsec budgets

Revision ID: 5eb0b279571d
Revises: d88650c401d7
Create Date: 2026-09-18 18:07:27.241397
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5eb0b279571d"
down_revision: str | None = "d88650c401d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The NOT NULL JSON columns below are added to populated tables, so each
    # is created with a server default to backfill and the default is then
    # dropped: the application always supplies a value, and leaving one in
    # place would hide a future missing one.
    op.add_column("rules_of_engagement", sa.Column("code_scope", sa.JSON(), nullable=True))
    op.add_column(
        "rules_of_engagement",
        sa.Column("appsec_budgets", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    )
    op.alter_column("rules_of_engagement", "appsec_budgets", server_default=None)
    op.add_column("targets", sa.Column("code_repo_ref", sa.String(length=2048), nullable=True))
    op.add_column(
        "targets",
        sa.Column("code_languages", sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
    )
    op.alter_column("targets", "code_languages", server_default=None)
    op.add_column(
        "targets",
        sa.Column(
            "code_build_manifest_paths", sa.JSON(), nullable=False, server_default=sa.text("'[]'")
        ),
    )
    op.alter_column("targets", "code_build_manifest_paths", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("targets", "code_build_manifest_paths")
    op.drop_column("targets", "code_languages")
    op.drop_column("targets", "code_repo_ref")
    op.drop_column("rules_of_engagement", "appsec_budgets")
    op.drop_column("rules_of_engagement", "code_scope")
    # ### end Alembic commands ###
