"""findings

Revision ID: 7fb3c0b81e34
Revises: 8c8d98669e95
Create Date: 2026-09-18 19:45:13.156393
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7fb3c0b81e34"
down_revision: str | None = "8c8d98669e95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "findings",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("fingerprint", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "AI_SECURITY",
                "API_SECURITY",
                "INFRASTRUCTURE",
                "DESIGN",
                name="finding_category_enum",
            ),
            nullable=False,
        ),
        sa.Column("probe_id", sa.String(length=200), nullable=False),
        sa.Column("probe_version", sa.String(length=50), nullable=False),
        sa.Column("surface", sa.String(length=2048), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INFORMATIONAL", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="finding_severity_enum"
            ),
            nullable=False,
        ),
        sa.Column("severity_rationale", sa.Text(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum("LOW", "MEDIUM", "HIGH", "DESIGN_REVIEW", name="finding_confidence_enum"),
            nullable=False,
        ),
        sa.Column(
            "stability",
            sa.Enum("DETERMINISTIC", "PROBABILISTIC", "SINGLE_SHOT", name="finding_stability_enum"),
            nullable=False,
        ),
        sa.Column("risk_model", sa.String(length=50), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("risk_inputs", sa.JSON(), nullable=False),
        sa.Column("attack_success_rate", sa.JSON(), nullable=True),
        sa.Column("control_success_rate", sa.JSON(), nullable=True),
        sa.Column("cvss_v4", sa.JSON(), nullable=True),
        sa.Column("aivss", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("impact", sa.Text(), nullable=False),
        sa.Column("remediation", sa.Text(), nullable=False),
        sa.Column("evidence_ref", sa.String(length=80), nullable=True),
        sa.Column("reproduction", sa.JSON(), nullable=False),
        sa.Column("mappings", sa.JSON(), nullable=False),
        sa.Column("mapping_versions", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "CONFIRMED",
                "FALSE_POSITIVE",
                "ACCEPTED_RISK",
                "IN_REMEDIATION",
                "REMEDIATED",
                "RETEST_REQUIRED",
                "CLOSED",
                name="finding_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("status_changed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("times_seen", sa.Integer(), nullable=False),
        sa.Column("first_run_id", sa.UUID(), nullable=True),
        sa.Column("last_run_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["first_run_id"], ["assessment_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["last_run_id"], ["assessment_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["status_changed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "fingerprint", name="uq_finding_org_fingerprint"),
    )
    op.create_index(op.f("ix_findings_fingerprint"), "findings", ["fingerprint"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_findings_fingerprint"), table_name="findings")
    op.drop_table("findings")
    # ### end Alembic commands ###
    # drop_table leaves the Postgres ENUM types behind, so a downgrade
    # followed by an upgrade would fail with "type ... already exists".
    for enum_name in (
        "finding_status_enum",
        "finding_stability_enum",
        "finding_confidence_enum",
        "finding_severity_enum",
        "finding_category_enum",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
