"""assessment runs and run events

Revision ID: 8ac60b818f52
Revises: 1be05aad205b
Create Date: 2026-09-18 11:20:24.867900
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8ac60b818f52"
down_revision: str | None = "1be05aad205b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_runs",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "EXPIRED",
                name="run_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("profile", sa.String(length=50), nullable=False),
        sa.Column("safe_mode", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("authorization_confirmed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("authorization_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checks_total", sa.Integer(), nullable=False),
        sa.Column("checks_completed", sa.Integer(), nullable=False),
        sa.Column("requests_used", sa.Integer(), nullable=False),
        sa.Column("requests_blocked", sa.Integer(), nullable=False),
        sa.Column("authorization_digest", sa.String(length=71), nullable=True),
        sa.Column("roe_digest", sa.String(length=71), nullable=True),
        sa.Column("halted_reason", sa.String(length=500), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("celery_task_id", sa.String(length=155), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["authorization_confirmed_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "run_events",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "QUEUED",
                "STARTED",
                "CHECK_STARTED",
                "CHECK_COMPLETED",
                "REQUEST_BLOCKED",
                "HALTED",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="run_event_kind_enum",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["assessment_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_events")
    op.drop_table("assessment_runs")
    # ### end Alembic commands ###
    # drop_table leaves the Postgres ENUM types behind, so a downgrade followed
    # by an upgrade would fail with "type ... already exists".
    sa.Enum(name="run_event_kind_enum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="run_status_enum").drop(op.get_bind(), checkfirst=True)
