"""surface body fields and synthetic accounts

Revision ID: c0a83fd9f643
Revises: 8ac60b818f52
Create Date: 2026-09-18 11:57:05.700689
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c0a83fd9f643"
down_revision: str | None = "8ac60b818f52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "synthetic_accounts",
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("credential_env_var", sa.String(length=200), nullable=False),
        sa.Column("header_name", sa.String(length=100), nullable=False),
        sa.Column("value_template", sa.String(length=200), nullable=False),
        sa.Column("owned_object_ids", sa.JSON(), nullable=False),
        sa.Column("is_privileged", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_id", "label", name="uq_synthetic_account_target_label"),
    )
    # ### end Alembic commands ###
    # Added NOT NULL to a table that already has rows, so each column is
    # created with a server default to backfill existing endpoints, and the
    # default is then dropped: the application always supplies a value, and
    # leaving a default behind would hide a future missing one.
    op.add_column(
        "surface_endpoints",
        sa.Column("body_fields", sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
    )
    op.add_column(
        "surface_endpoints",
        sa.Column("body_required", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.alter_column("surface_endpoints", "body_fields", server_default=None)
    op.alter_column("surface_endpoints", "body_required", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surface_endpoints", "body_required")
    op.drop_column("surface_endpoints", "body_fields")
    op.drop_table("synthetic_accounts")
    # ### end Alembic commands ###
