"""ai drafts

Revision ID: d3a4e6b2d655
Revises: 1de6a8485e08
Create Date: 2026-09-18 18:53:11.652770
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d3a4e6b2d655"
down_revision: str | None = "1de6a8485e08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_drafts",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("scan_result_id", sa.UUID(), nullable=True),
        sa.Column(
            "field",
            sa.Enum(
                "EXPLANATION",
                "REMEDIATION",
                "SEVERITY_RATIONALE",
                "RUN_SUMMARY",
                name="ai_draft_field_enum",
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_template_id", sa.String(length=200), nullable=False),
        sa.Column("prompt_template_version", sa.String(length=50), nullable=False),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["accepted_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requested_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["assessment_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_result_id"], ["scan_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_drafts")
    # ### end Alembic commands ###
    # drop_table leaves the Postgres ENUM behind, so a downgrade followed by
    # an upgrade would fail with "type ... already exists".
    sa.Enum(name="ai_draft_field_enum").drop(op.get_bind(), checkfirst=True)
