"""target adapter config and declared tools

Revision ID: d88650c401d7
Revises: d8d9a5638578
Create Date: 2026-09-18 12:39:35.172305
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d88650c401d7"
down_revision: str | None = "d8d9a5638578"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("targets", sa.Column("adapter_kind", sa.String(length=50), nullable=True))
    # NOT NULL on a populated table: create with a default to backfill,
    # then drop it so a future missing value is an error, not a silent empty.
    op.add_column(
        "targets",
        sa.Column("adapter_config", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    )
    op.add_column(
        "targets",
        sa.Column("declared_tools", sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
    )
    op.alter_column("targets", "adapter_config", server_default=None)
    op.alter_column("targets", "declared_tools", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("targets", "declared_tools")
    op.drop_column("targets", "adapter_config")
    op.drop_column("targets", "adapter_kind")
    # ### end Alembic commands ###
