"""run findings count

Revision ID: d8d9a5638578
Revises: a5ce92c3aac3
Create Date: 2026-09-18 12:01:10.833484
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d8d9a5638578"
down_revision: str | None = "a5ce92c3aac3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL on a table that already has rows: create with a default to
    # backfill, then drop it so a future missing value is an error rather
    # than a silent zero.
    op.add_column(
        "assessment_runs",
        sa.Column("findings_reported", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    op.alter_column("assessment_runs", "findings_reported", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessment_runs", "findings_reported")
    # ### end Alembic commands ###
