"""targets, authorizations, rules_of_engagement

Revision ID: ffdd5b9970bc
Revises: 5e19add79ace
Create Date: 2026-09-18 07:08:52.361125
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ffdd5b9970bc"
down_revision: str | None = "5e19add79ace"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "targets",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "environment",
            sa.Enum("STAGING", "TEST", "DEV", "PRODUCTION", name="target_environment_enum"),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "LLM_APP",
                "AGENT",
                "RAG",
                "API",
                "MCP_SERVER",
                "MODEL_ENDPOINT",
                name="target_kind_enum",
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "authorizations",
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("authorized_by_name", sa.String(length=200), nullable=False),
        sa.Column("authorized_by_role", sa.String(length=100), nullable=False),
        sa.Column("authorized_by_email", sa.String(length=320), nullable=False),
        sa.Column("reference", sa.String(length=500), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_by_user_id", sa.UUID(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["accepted_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_id"),
    )
    op.create_table(
        "rules_of_engagement",
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("allowed_domains", sa.JSON(), nullable=False),
        sa.Column("excluded_domains", sa.JSON(), nullable=False),
        sa.Column("allowed_ip_ranges", sa.JSON(), nullable=False),
        sa.Column("allowed_paths", sa.JSON(), nullable=False),
        sa.Column("excluded_paths", sa.JSON(), nullable=False),
        sa.Column("allowed_methods", sa.JSON(), nullable=False),
        sa.Column("forbidden_headers", sa.JSON(), nullable=False),
        sa.Column("budgets", sa.JSON(), nullable=False),
        sa.Column("safe_mode", sa.Boolean(), nullable=False),
        sa.Column("blackout_windows", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rules_of_engagement")
    op.drop_table("authorizations")
    op.drop_table("targets")
    # ### end Alembic commands ###
    # See the equivalent note in 5e19add79ace: op.drop_table does not drop
    # the ENUM types Postgres created alongside these columns.
    sa.Enum(name="target_environment_enum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="target_kind_enum").drop(op.get_bind(), checkfirst=True)
